### ISSUE TITLE
Slim deze constraint namen

### ISSUE THREAD

**Issue by JeroenHeemskerk** [uknowwho/educom-webshop-oop-1713521403#24]
Hoi Florian,
Ik zag in de SQL de namen van de constraints 
https://github.com/uknowwho/educom-webshop-oop-1713521403/blob/c89face27dfe21e9ad89b0ec6028f07f4b4bb6d0/florians_webshop.sql#L197-L206
Dit is iets wat ik nog nergens heb gezien, maar wat een logische naam geeft aan de constraints **chapeau**
🥇 

ik zou de laatste twee noemen
```sql
   ADD CONSTRAINT `orderhasorderproducts` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`), 
   ADD CONSTRAINT `producthasorderproducts` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`); 
```
> Tip: je kan ook nog snake_case gebruiken
```sql
   ADD CONSTRAINT `order_has_order_products` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`), 
   ADD CONSTRAINT `product_has_order_products` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`); 
```

**Comment by uknowwho** [comment]
Dankjewel!
